### ISSUE TITLE
Sample code is incompatible with latest npm package versions

### ISSUE THREAD

**Issue by mauricefaeh** [PacktPublishing/Learning-GraphQL-and-Relay#2]
Chapter 1:
- Sample code is incompatible with newer/latest npm package versions.
  - Error: "db.collection is not a function"

**Comment by jhorgint** [comment]
hello my friend after a hard struggling I've gotten run the code, check out my repository

https://github.com/jhorgint/Learning-GraphQL-and-Relay

**Comment by gaurav-packt** [comment]
Thanks for the update.
